name: Build and deploy Node.js app to Azure Web App - ubuntu-health-api

on:
  push:
    branches:
      - main
    paths:
      - 'clinic-system/server/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:

env:
  SERVER_DIR: clinic-system/server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: ${{ env.SERVER_DIR }}
        run: npm install

      - name: Build
        working-directory: ${{ env.SERVER_DIR }}
        run: npm run build --if-present

      - name: Test
        working-directory: ${{ env.SERVER_DIR }}
        env:
          SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.SERVER_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68788B7BCF074A3082226B014843A318 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1134F8A458804654805512A4BE9FB264 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35D031B765DE4A1E845608BC0B3978C2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ubuntu-health-api
          slot-name: Production
          package: .
